
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.8

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install ruby-full rsync -y
            sudo gem install sass
            export PIPENV_VENV_IN_PROJECT=1
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: Lint
          command: |
            make lint-assets
            make lint-code

      - run:
          name: Publish locally
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              make publish-demo
            else
              make publish
            fi

      - run:
          name: Upload to DigitalOcean
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              rsync -e "ssh -o StrictHostKeyChecking=no" -avz output/ $HTTP_USER@$HTTP_SERVER:$HTTP_DEMO_FOLDER
            else
              rsync -e "ssh -o StrictHostKeyChecking=no" -avz output/ $HTTP_USER@$HTTP_SERVER:$HTTP_FOLDER
            fi

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - store_artifacts:
          path: output
          destination: output