
version: 2
jobs:
  build:
    docker:
      - image: casimir/python-circleci-rsync

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Pipfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            export PIPENV_VENV_IN_PROJECT=1
            sudo pip install pipenv
            pipenv install --dev

      - run:
          name: Publish locally
          command: |
            make publish

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "Pipfile.lock" }}

      - store_artifacts:
          path: output
          destination: output